config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
    delete "logout", to: "devise/sessions#destroy"
    get "settings", to: "devise/registrations#edit"
  end

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :posts, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :posts
    delete "likes", to: "posts/likes#destroy"
  end

  resources :comments, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :comments
    delete "likes", to: "comments/likes#destroy"
  end

  resources :replies, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :replies
    delete "likes", to: "replies/likes#destroy"
  end

  post "follow", to: "relationships#create", as: "follow"
  delete "unfollow", to: "relationships#destroy", as: "unfollow"

  resources :notifications, only: [:index]

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create], module: :conversations
    collection do
      get "search", to: "conversations/search#index"
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Likeable

  belongs_to :user
  belongs_to :post

  has_many :replies, dependent: :destroy

  has_rich_text :content

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, :post_id, presence: true

  def replies_count
    replies.not_reply.count
  end
end

app/controllers/comments/likes_controller.rb
# frozen_string_literal: true

module Comments
  class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_comment

    def create
      @comment.like(current_user)
      send_notification
      update_likes_form
    end

    def destroy
      @comment.unlike(current_user)
      update_likes_form
    end

    private

    def set_comment
      @comment = Comment.find_by(id: params[:comment_id])

      unless @comment
        flash[:alert] = "Comment not found."
        redirect_to(root_path)
      end
    end

    def send_notification
      Notifications::LikeNotifierJob.perform_async({
        likeable_type: "Comment",
        likeable_id: @comment.id,
        user_id: current_user.id,
      }.stringify_keys)
    end

    def update_likes_form
      render(turbo_stream:
        turbo_stream.replace(
          "comment_#{params[:comment_id]}-likes",
          partial: "likes/like_form",
          locals: { model: @comment },
        ))
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def show
    @comment = Comment.includes(:likers, :likes, :replies, :post, :rich_text_content).find_by(id: params[:id])
    return redirect_to(root_path) unless @comment

    @pagy, @replies = pagy(@comment.replies.not_reply.newest.includes(:user, :likers, :likes), items: 10)
    @reply = Reply.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      send_notification
      flash[:notice] = "Comment created"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_to(post_path(@comment.post))
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    if @comment&.user == current_user
      @comment.destroy
      flash[:notice] = "Comment deleted"
      redirect_to(post_path(@comment.post))
    else
      flash[:alert] = "Something went wrong"
      redirect_to(root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def send_notification
    Notifications::CommentNotifierJob.perform_async({
      comment_id: @comment.id,
      actor_id: current_user.id,
    }.stringify_keys)
  end
end

app/views/comments/_comment.html.erb
<div class="container my-3 border-bottom">
  <div class="d-flex align-items-center">
    <%= image_tag comment.user.avatar.variant(:thumb), class: "rounded-circle me-3", alt: "User Avatar" %>
    <div>
      <h5 class="card-title mb-0"><%= link_to display_name(comment.user), user_path(comment.user), style: "color:black; text-decoration:none" %></h5>
      <p class="card-text"><small class="text-muted"><%= time_ago_in_words(comment.created_at) %> ago </small></p>
    </div>
    <div class="ms-auto">
    <%= link_to comment_path(comment), style:"color:black;text-decoration:none" do %>
      <span class="ms-2"><%= comment.replies_count %></span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="black" class="bi bi-chat" viewBox="0 0 16 16">
        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
      </svg>
    <% end %>
      <%= render 'likes/like_form', model: comment %>
    <% if comment.user == current_user %>
          <%= link_to comment_path(comment), data:{"turbo-method": :delete}, style:"color:red; text-decoration:none" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
              <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
            </svg>
          <% end %>
        <% end %>
    </div>
  </div>
  <p class="my-2"><%= comment.content %></p>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/trix_helper' %>

<%= form_with model: @comment do |f| %>
  <%= f.hidden_field :post_id, value: commentable.id %>
  <%= f.rich_text_area :content, class: "form-control mb-3", rows: "3", placeholder: "Write something..." %>
  <div class="d-flex justify-content-end">
    <%= f.submit "Comment", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 border-end">
      <div class="d-flex align-items-start">
        <%= image_tag current_user.avatar.variant(:thumb), class: "rounded-circle me-3", alt: "User Avatar" %>
        <div>
          <h6><%= display_name(current_user) %></h6>
          <%= render "replies/form", comment: @comment, replying_to: nil, reply: @reply %>
        </div>
      </div>
    </div>
    <div class="col-md-6 border-end">
      <%= render @comment.post %>
      <h4>Comment</h4>
      <%= render @comment %>

      <h4>Replies</h4>
      <% if !@replies.empty? %>
        <% @replies.each do |reply| %>
          <%= render reply %>
        <% end %>
        <%== pagy_bootstrap_nav(@pagy) %>
      <% else %>
        <p>No replies yet</p>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= render 'shared/side_bar' %>
    </div>
  </div>
</div>