config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  devise_for :users,
    controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "register", to: "devise/registrations#new"
    delete "logout", to: "devise/sessions#destroy"
    get "settings", to: "devise/registrations#edit"
  end

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :posts, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :posts
    delete "likes", to: "posts/likes#destroy"
  end

  resources :comments, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :comments
    delete "likes", to: "comments/likes#destroy"
  end

  resources :replies, only: [:create, :destroy, :show] do
    resources :likes, only: [:create], module: :replies
    delete "likes", to: "replies/likes#destroy"
  end

  post "follow", to: "relationships#create", as: "follow"
  delete "unfollow", to: "relationships#destroy", as: "unfollow"

  resources :notifications, only: [:index]

  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create], module: :conversations
    collection do
      get "search", to: "conversations/search#index"
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, :followed_id, presence: true
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:create, :destroy]

  def create
    current_user.follow(@user)
    send_notification
    respond_to do |format|
      format.html { redirect_back(fallback_location: user_path(@user)) }
      format.turbo_stream
    end
  end

  def destroy
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: user_path(@user)) }
      format.turbo_stream
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])
    unless @user
      flash[:alert] = "Unable to find user with id #{params[:user_id]}"
      redirect_back(fallback_location: root_path)
    end
  end

  def send_notification
    Notifications::FollowNotifierJob.perform_async({
      follower_id: current_user.id,
      followed_id: @user.id,
    }.stringify_keys)
  end
end

app/views/relationships/_form.html.erb
<% if current_user.following?(user) %>
  <%= link_to unfollow_path(user_id: user.id), data: {"turbo-method": :delete}, style:"color:black;text-decoration:none" do %>
    <button class="btn btn-primary">Unfollow</button>
  <% end %>
<% else %>
  <%= link_to follow_path(user_id: user.id), data: {"turbo-method": :post}, style:"color:black;text-decoration:none" do %>
    <button class="btn btn-primary">Follow</button>
  <% end %>
<% end %>

app/views/relationships/_relationship.html.erb
<div class="card mt-3">
  <div class="card-body">
    <div class="row">
      <div class="col text-center border-end">
        <%= turbo_frame_tag "followers" do %>
          <h3><%= user.followers.length %></h3>
        <% end %>
        <p><%= link_to "Followers", followers_user_path(user) %></p>
      </div>
      <div class="col text-center">
        <h3><%= user.following.length %></h3>
        <p><%= link_to "Following", following_user_path(user) %> </p>
      </div>
    </div>
    <% unless current_user == user %>
    <div class="row mt-3">
      <div class="col text-center">
      <%= turbo_frame_tag "follow-form" do %>
        <%= render 'relationships/form', user: user %>
      <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/relationships/create.turbo_stream.erb
<%= turbo_stream.update "follow-form" do %>
  <%= render partial: "relationships/form", locals: {user: @user } %>
<% end %>

<%= turbo_stream.update "followers" do %>
 <h3><%= @user.followers.length %></h3>
<% end %>

app/views/relationships/destroy.turbo_stream.erb
<%= turbo_stream.update "follow-form" do %>
  <%= render partial: "relationships/form", locals: {user: @user } %>
<% end %>

<%= turbo_stream.update "followers" do %>
 <h3><%= @user.followers.length %></h3>
<% end %>